export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
export const CHANGE_CART_PRODUCT = 'CHANGE_CART_PRODUCT';
export const CHANGE_CART_PRODUCT_QUANTITY = 'CHANGE_CART_PRODUCT_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';